groups:
- name: library
  rules:

  # Alert for any instance that is unreachable for >1 minutes.
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than a minute."

- name: SLOs-http_requests_total
  rules:
  - alert: ErrorBudgetBurn
    annotations:
      message: 'High error budget burn for job=prometheus (current value: {{ $value }})'
    expr: |
      sum(http_requests_total:burnrate5m{job="prometheus"}) > (14.40 * (1-0.99800))
      and
      sum(http_requests_total:burnrate1h{job="prometheus"}) > (14.40 * (1-0.99800))
    for: 2m
    labels:
      job: prometheus
      severity: critical
  - alert: ErrorBudgetBurn
    annotations:
      message: 'High error budget burn for job=prometheus (current value: {{ $value }})'
    expr: |
      sum(http_requests_total:burnrate30m{job="prometheus"}) > (6.00 * (1-0.99800))
      and
      sum(http_requests_total:burnrate6h{job="prometheus"}) > (6.00 * (1-0.99800))
    for: 15m
    labels:
      job: prometheus
      severity: critical
  - alert: ErrorBudgetBurn
    annotations:
      message: 'High error budget burn for job=prometheus (current value: {{ $value }})'
    expr: |
      sum(http_requests_total:burnrate2h{job="prometheus"}) > (3.00 * (1-0.99800))
      and
      sum(http_requests_total:burnrate1d{job="prometheus"}) > (3.00 * (1-0.99800))
    for: 1h
    labels:
      job: prometheus
      severity: warning
  - alert: ErrorBudgetBurn
    annotations:
      message: 'High error budget burn for job=prometheus (current value: {{ $value }})'
    expr: |
      sum(http_requests_total:burnrate6h{job="prometheus"}) > (1.00 * (1-0.99800))
      and
      sum(http_requests_total:burnrate3d{job="prometheus"}) > (1.00 * (1-0.99800))
    for: 3h
    labels:
      job: prometheus
      severity: warning
  - expr: |
      sum(rate(http_requests_total{job="prometheus",code=~"5.."}[1d]))
      /
      sum(rate(http_requests_total{job="prometheus"}[1d]))
    labels:
      job: prometheus
    record: http_requests_total:burnrate1d
  - expr: |
      sum(rate(http_requests_total{job="prometheus",code=~"5.."}[1h]))
      /
      sum(rate(http_requests_total{job="prometheus"}[1h]))
    labels:
      job: prometheus
    record: http_requests_total:burnrate1h
  - expr: |
      sum(rate(http_requests_total{job="prometheus",code=~"5.."}[2h]))
      /
      sum(rate(http_requests_total{job="prometheus"}[2h]))
    labels:
      job: prometheus
    record: http_requests_total:burnrate2h
  - expr: |
      sum(rate(http_requests_total{job="prometheus",code=~"5.."}[30m]))
      /
      sum(rate(http_requests_total{job="prometheus"}[30m]))
    labels:
      job: prometheus
    record: http_requests_total:burnrate30m
  - expr: |
      sum(rate(http_requests_total{job="prometheus",code=~"5.."}[3d]))
      /
      sum(rate(http_requests_total{job="prometheus"}[3d]))
    labels:
      job: prometheus
    record: http_requests_total:burnrate3d
  - expr: |
      sum(rate(http_requests_total{job="prometheus",code=~"5.."}[5m]))
      /
      sum(rate(http_requests_total{job="prometheus"}[5m]))
    labels:
      job: prometheus
    record: http_requests_total:burnrate5m
  - expr: |
      sum(rate(http_requests_total{job="prometheus",code=~"5.."}[6h]))
      /
      sum(rate(http_requests_total{job="prometheus"}[6h]))
    labels:
      job: prometheus
    record: http_requests_total:burnrate6h

- name: SLOs-http_request_duration_seconds
  rules:
  - alert: LatencyBudgetBurn
    annotations:
      message: 'High requests latency budget burn for job=prometheus,latency=0.20000000000000001 (current value: {{ $value }})'
    expr: |
      (
        latencytarget:http_request_duration_seconds:rate1h{job="prometheus",latency="0.20000000000000001"} > (14.4*1.000000)
        and
        latencytarget:http_request_duration_seconds:rate5m{job="prometheus",latency="0.20000000000000001"} > (14.4*1.000000)
      )
      or
      (
        latencytarget:http_request_duration_seconds:rate6h{job="prometheus",latency="0.20000000000000001"} > (6*1.000000)
        and
        latencytarget:http_request_duration_seconds:rate30m{job="prometheus",latency="0.20000000000000001"} > (6*1.000000)
      )
    labels:
      job: prometheus
      latency: "0.20000000000000001"
      severity: critical
  - alert: LatencyBudgetBurn
    annotations:
      message: 'High requests latency budget burn for job=prometheus,latency=0.20000000000000001 (current value: {{ $value }})'
    expr: |
      (
        latencytarget:http_request_duration_seconds:rate1d{job="prometheus",latency="0.20000000000000001"} > (3*1.000000)
        and
        latencytarget:http_request_duration_seconds:rate2h{job="prometheus",latency="0.20000000000000001"} > (3*1.000000)
      )
      or
      (
        latencytarget:http_request_duration_seconds:rate3d{job="prometheus",latency="0.20000000000000001"} > (1.000000)
        and
        latencytarget:http_request_duration_seconds:rate6h{job="prometheus",latency="0.20000000000000001"} > (1.000000)
      )
    labels:
      job: prometheus
      latency: "0.20000000000000001"
      severity: warning
  - expr: |
      1 - (
        sum(rate(http_request_duration_seconds_bucket{job="prometheus",le="0.20000000000000001",code!~"5.."}[5m]))
        /
        sum(rate(http_request_duration_seconds_count{job="prometheus"}[5m]))
      )
    labels:
      job: prometheus
      latency: "0.20000000000000001"
    record: latencytarget:http_request_duration_seconds:rate5m
  - expr: |
      1 - (
        sum(rate(http_request_duration_seconds_bucket{job="prometheus",le="0.20000000000000001",code!~"5.."}[30m]))
        /
        sum(rate(http_request_duration_seconds_count{job="prometheus"}[30m]))
      )
    labels:
      job: prometheus
      latency: "0.20000000000000001"
    record: latencytarget:http_request_duration_seconds:rate30m
  - expr: |
      1 - (
        sum(rate(http_request_duration_seconds_bucket{job="prometheus",le="0.20000000000000001",code!~"5.."}[1h]))
        /
        sum(rate(http_request_duration_seconds_count{job="prometheus"}[1h]))
      )
    labels:
      job: prometheus
      latency: "0.20000000000000001"
    record: latencytarget:http_request_duration_seconds:rate1h
  - expr: |
      1 - (
        sum(rate(http_request_duration_seconds_bucket{job="prometheus",le="0.20000000000000001",code!~"5.."}[2h]))
        /
        sum(rate(http_request_duration_seconds_count{job="prometheus"}[2h]))
      )
    labels:
      job: prometheus
      latency: "0.20000000000000001"
    record: latencytarget:http_request_duration_seconds:rate2h
  - expr: |
      1 - (
        sum(rate(http_request_duration_seconds_bucket{job="prometheus",le="0.20000000000000001",code!~"5.."}[6h]))
        /
        sum(rate(http_request_duration_seconds_count{job="prometheus"}[6h]))
      )
    labels:
      job: prometheus
      latency: "0.20000000000000001"
    record: latencytarget:http_request_duration_seconds:rate6h
  - expr: |
      1 - (
        sum(rate(http_request_duration_seconds_bucket{job="prometheus",le="0.20000000000000001",code!~"5.."}[1d]))
        /
        sum(rate(http_request_duration_seconds_count{job="prometheus"}[1d]))
      )
    labels:
      job: prometheus
      latency: "0.20000000000000001"
    record: latencytarget:http_request_duration_seconds:rate1d
  - expr: |
      1 - (
        sum(rate(http_request_duration_seconds_bucket{job="prometheus",le="0.20000000000000001",code!~"5.."}[3d]))
        /
        sum(rate(http_request_duration_seconds_count{job="prometheus"}[3d]))
      )
    labels:
      job: prometheus
      latency: "0.20000000000000001"
    record: latencytarget:http_request_duration_seconds:rate3d
