version: '3'

services:

  database:
      image: 'postgres:latest'
      container_name: db

      # By default, a Postgres database is running on the 5432 port.
      # If we want to access the database from our computer (outside the container),
      # we must share the port with our computer's port.
      # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
      # Note: You are free to change your computer's port,
      # but take into consideration that it will change the way
      # you are connecting to your database.
      ports:
        - 5432:5432

      environment:
        POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
        POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
        POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)

      healthcheck:
        test: pg_isready -U username -d default_database
      # The `volumes` tag allows us to share a folder with our container.
      # Its syntax is as follows: [folder path on our machine]:[folder path to retrieve in the container]
      volumes:
        # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path.
        # It means that every time the repository is modifying the data inside
        # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`.
        # You don't need to create the `db-data` folder. Docker Compose will do it for you.
        - ./db-data/:/var/lib/postgresql/data/

  app:
    image: 'esuminski/k8-library:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/default_database
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password

    volumes:
      - ../logs/:/logs/


  