apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: library-prometheus-rules
  labels:
    release: prometheus
spec:
  groups:
  - name: librarySLOs-http_request_latency
    rules:
    - expr: |
        1 - 
        (( sum(rate(http_server_requests_seconds_sum{job="library-service", status!~"5.."}[5m]))
        /
        sum(rate(http_server_requests_seconds_count{job="library-service", status!~"5.."}[5m])) ) < 1.2 )
        /
        (( sum(rate(http_server_requests_seconds_sum{job="library-service"}[5m]))
        /
        sum(rate(http_server_requests_seconds_count{job="library-service"}[5m])) ) >= 0 )
      labels:
        job: library-service
      record: library_service:http_request_latency:burnrate5m