apiVersion: v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: default
  labels:
    set: postgres
spec:
  containers:
  - name: postgres-container
    image: postgres:latest
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_PASSWORD
        value: password
      - name: POSTGRES_USER
        value: username
      - name: POSTGRES_DB
        value: default_database
      - name: PGDATA
        value: /var/lib/postgresql/data/pgdata
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: db-data
  volumes:
    - name: db-data
      emptyDir: {}